import type { NichePreset } from "./types";

const baseSectionOrder = [
  "hero",
  "trustStrip",
  "problemVisualization",
  "diagnosticTool",
  "services",
  "proof",
  "process",
  "photoUploadQuoteFlow",
  "faq",
  "finalCTA",
];

const contractorTrust = [
  "Licensed & insured",
  "Real local crew",
  "Free written estimate",
  "Photo-documented work",
  "Manufacturer-grade materials",
];

const contractorRiskReducers = [
  "No commitment to inspect",
  "Same-day reply during business hours",
  "Written quote with line items",
  "Workmanship warranty",
];

export const NICHE_PRESETS: Record<string, NichePreset> = {
  roofing: {
    slug: "roofing",
    label: "Roofing",
    categoryGroup: "home-services-contractor",
    estimatedLeadValue: 1200,
    defaultServices: [
      "Emergency roof repair",
      "Full roof replacement",
      "Shingle repair",
      "Flat roof systems",
      "Storm & insurance work",
    ],
    buyerPains: [
      "Active roof leak",
      "Storm damage",
      "Missing or curled shingles",
      "Insurance claim pressure",
      "Worry about hidden water damage",
    ],
    highValueServices: ["Full replacement", "Insurance restoration", "Flat roof"],
    leadMagnet: "Roof Leak Severity Check",
    primaryCTA: "Get a Free Roof Inspection",
    secondaryCTA: "Upload a Photo for a Fast Estimate",
    quoteFlow: [
      {
        id: "issue",
        question: "What's happening with your roof?",
        type: "choice",
        options: [
          "Active leak",
          "Storm or wind damage",
          "Missing or curled shingles",
          "Old roof, planning replacement",
          "Other",
        ],
        required: true,
      },
      {
        id: "urgency",
        question: "How urgent is this?",
        type: "choice",
        options: ["Today", "This week", "This month", "Just planning"],
        required: true,
      },
      {
        id: "roofType",
        question: "What kind of roof do you have?",
        type: "choice",
        options: ["Asphalt shingle", "Flat / membrane", "Metal", "Not sure"],
      },
      {
        id: "photo",
        question: "Add a photo so we can give you a faster estimate",
        type: "upload",
        helper: "Optional — but it usually cuts the quote time in half.",
      },
      {
        id: "address",
        question: "Address of the property",
        type: "text",
        required: true,
      },
      {
        id: "contact",
        question: "Where should we send the inspection time?",
        type: "contact",
        required: true,
      },
    ],
    trustPoints: contractorTrust,
    faqs: [
      { q: "Do you inspect for free?", a: "Yes — local inspections are free with no commitment to book the work." },
      { q: "How fast can you come out for a leak?", a: "Active leaks are prioritized same-day or next-day during the season." },
      { q: "Do you work with insurance?", a: "Yes, we document everything photographically and can speak with adjusters." },
    ],
    riskReducers: contractorRiskReducers,
    visualDirection: "Cinematic dark, storm-grade, glowing leak hotspot, urgent but trustworthy.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "storm-orange",
    motionPreset: "cinematic-pin",
    threeDPreset: "roof-plane-rain",
    accentColor: "#ff6a3d",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Stop the leak before it becomes the wall.",
      subheadline:
        "Local roof inspections in {city} — photo-documented, written quote, no commitment.",
    },
    problem: {
      title: "A small leak today is a $12,000 problem in a year.",
      body: "Water travels. By the time you see the stain on the ceiling, the deck, insulation and drywall are already involved. The fastest way to keep it cheap is to check it now.",
    },
    finalCta: {
      title: "Get your roof checked this week.",
      body: "Tell us what's happening and we'll send a written estimate after a free, no-pressure inspection.",
    },
  },

  "attic-insulation": {
    slug: "attic-insulation",
    label: "Attic Insulation",
    categoryGroup: "home-services-contractor",
    estimatedLeadValue: 900,
    defaultServices: [
      "Attic insulation top-up",
      "Spray foam",
      "Air sealing",
      "Ventilation correction",
      "Energy rebate paperwork",
    ],
    buyerPains: [
      "High heating/cooling bills",
      "Hot upstairs / cold downstairs",
      "Ice dams in winter",
      "Drafty rooms",
      "Older home with unknown insulation",
    ],
    highValueServices: ["Spray foam", "Full top-up", "Air sealing"],
    leadMagnet: "Attic Efficiency Check",
    primaryCTA: "Get Your Free Attic Assessment",
    secondaryCTA: "Estimate My Energy Loss",
    quoteFlow: [
      {
        id: "homeType",
        question: "What kind of home is it?",
        type: "choice",
        options: ["Detached", "Semi-detached", "Townhouse", "Bungalow", "Other"],
        required: true,
      },
      {
        id: "homeSize",
        question: "Roughly how big is the home?",
        type: "choice",
        options: ["Under 1,500 sq ft", "1,500–2,500", "2,500–3,500", "3,500+"],
      },
      {
        id: "comfort",
        question: "What's the main comfort issue?",
        type: "choice",
        options: ["Cold rooms", "Hot upstairs", "High bills", "Drafts", "Just curious"],
        required: true,
      },
      {
        id: "insulationAge",
        question: "When was the insulation last touched?",
        type: "choice",
        options: ["Never", "10+ years ago", "Recently", "Not sure"],
      },
      {
        id: "photo",
        question: "Optional: photo of your attic",
        type: "upload",
      },
      {
        id: "contact",
        question: "Best way to send the assessment time",
        type: "contact",
        required: true,
      },
    ],
    trustPoints: [
      "Certified installers",
      "Energy rebate help",
      "Manufacturer-grade materials",
      "Written report",
      "Local crew",
    ],
    faqs: [
      { q: "Are there rebates?", a: "Most homeowners qualify for a rebate program — we handle the paperwork with you." },
      { q: "How long does it take?", a: "Most homes take a single day with minimal disruption." },
      { q: "What about ventilation?", a: "Attic insulation only works if ventilation is right — we check both." },
    ],
    riskReducers: [
      "Free in-home assessment",
      "Written report with photos",
      "No upsell pressure",
      "Workmanship warranty",
    ],
    visualDirection: "Cinematic dark with thermal-orange particles escaping a house cutaway.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "thermal-orange",
    motionPreset: "cinematic-pin",
    threeDPreset: "house-heat-loss",
    accentColor: "#ff8a3d",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "You're paying to heat the sky.",
      subheadline:
        "Free attic efficiency check in {city}. Written report, real numbers, rebate help.",
    },
    problem: {
      title: "Most {city} attics leak heat like an open window.",
      body: "Older insulation settles, gets compressed, and stops doing its job. The bill keeps rising, the upstairs stays cold — and the fix is usually a single day of work.",
    },
    finalCta: {
      title: "See where your home is losing heat.",
      body: "Book a free attic assessment — written report, real numbers, no pressure to book.",
    },
  },

  hvac: {
    slug: "hvac",
    label: "HVAC",
    categoryGroup: "home-services-contractor",
    estimatedLeadValue: 1100,
    defaultServices: [
      "Furnace repair",
      "AC repair",
      "Furnace install",
      "AC install",
      "Tune-ups & maintenance",
    ],
    buyerPains: [
      "No heat / no cooling emergency",
      "Old system unreliable",
      "Uneven rooms",
      "Loud system",
      "High energy bills",
    ],
    highValueServices: ["Furnace install", "AC install", "Heat pump"],
    leadMagnet: "Home Comfort Score",
    primaryCTA: "Book a Free Comfort Assessment",
    secondaryCTA: "Get an Emergency Service Visit",
    quoteFlow: [
      {
        id: "issue",
        question: "What's going on?",
        type: "choice",
        options: [
          "No heat",
          "No cooling",
          "Old system, planning replacement",
          "Uneven rooms / comfort issue",
          "Just maintenance",
        ],
        required: true,
      },
      {
        id: "urgency",
        question: "How urgent is it?",
        type: "choice",
        options: ["Today", "This week", "This month", "Just planning"],
        required: true,
      },
      {
        id: "systemAge",
        question: "How old is the system?",
        type: "choice",
        options: ["Under 5 years", "5–10", "10–15", "15+", "Not sure"],
      },
      {
        id: "homeSize",
        question: "Home size",
        type: "choice",
        options: ["Under 1,500 sq ft", "1,500–2,500", "2,500–3,500", "3,500+"],
      },
      {
        id: "contact",
        question: "Where should we send the visit time?",
        type: "contact",
        required: true,
      },
    ],
    trustPoints: contractorTrust,
    faqs: [
      { q: "Do you do emergency calls?", a: "Yes — same-day during heating and cooling season." },
      { q: "Do you finance?", a: "Yes, options are available for new system installs." },
      { q: "Do you service my brand?", a: "We service all major brands. Tell us yours during booking." },
    ],
    riskReducers: contractorRiskReducers,
    visualDirection: "Calm dark with cool/warm airflow streams through an abstract home.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "comfort-blue",
    motionPreset: "cinematic-pin",
    threeDPreset: "airflow-home",
    accentColor: "#4d8bff",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Your home should feel right in every room.",
      subheadline:
        "Comfort-first HVAC service in {city}. Same-day repairs, honest replacements, real comfort.",
    },
    problem: {
      title: "Discomfort is a system problem, not a thermostat problem.",
      body: "Hot upstairs, cold basements, loud cycles — these are signs your system is fighting your home. We diagnose the actual cause, not just the symptom.",
    },
    finalCta: {
      title: "Book a comfort assessment.",
      body: "Tell us what you're feeling and we'll find what's actually causing it.",
    },
  },

  landscaping: {
    slug: "landscaping",
    label: "Landscaping",
    categoryGroup: "home-services-outdoor",
    estimatedLeadValue: 1500,
    defaultServices: [
      "Backyard design",
      "Sod & grading",
      "Garden installs",
      "Lighting",
      "Maintenance",
    ],
    buyerPains: [
      "Unused outdoor space",
      "Curb appeal",
      "Property value before sale",
      "Tired of doing it themselves",
      "No idea where to start",
    ],
    highValueServices: ["Full backyard transformation", "Hardscape + softscape combo"],
    leadMagnet: "Backyard Project Estimate",
    primaryCTA: "Plan My Outdoor Project",
    secondaryCTA: "Send Photos for a Fast Estimate",
    quoteFlow: [
      {
        id: "projectType",
        question: "What are we working on?",
        type: "choice",
        options: ["Full redesign", "Patio / hardscape", "Garden / softscape", "Maintenance"],
        required: true,
      },
      {
        id: "yardSize",
        question: "Roughly how big is the yard?",
        type: "choice",
        options: ["Small", "Medium", "Large", "Not sure"],
      },
      {
        id: "budget",
        question: "Where's your comfort range?",
        type: "choice",
        options: ["Under $5k", "$5k–$15k", "$15k–$30k", "$30k+"],
      },
      {
        id: "timeline",
        question: "When would you like it done?",
        type: "choice",
        options: ["ASAP", "This season", "Next season", "Just exploring"],
      },
      {
        id: "photo",
        question: "Photos of the space (optional)",
        type: "upload",
      },
      {
        id: "contact",
        question: "Best way to send the estimate",
        type: "contact",
        required: true,
      },
    ],
    trustPoints: [
      "Local design crew",
      "Real installed projects",
      "Detailed written estimate",
      "Workmanship warranty",
      "On-site consultation",
    ],
    faqs: [
      { q: "Do you charge for estimates?", a: "Free written estimates after a quick on-site consultation." },
      { q: "Do you handle design and install?", a: "Yes, design + install in one team to keep accountability simple." },
      { q: "Do you guarantee plant health?", a: "We provide care guidance and warranty terms in the written quote." },
    ],
    riskReducers: ["Free consultation", "Written quote", "Stage payments", "Workmanship warranty"],
    visualDirection: "Layered terrain slabs with grass/stone materials, calm depth.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "garden-green",
    motionPreset: "cinematic-pin",
    threeDPreset: "terrain-layers",
    accentColor: "#39d98a",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "The backyard you actually live in.",
      subheadline:
        "Design + install for {city} homeowners who are done settling for a yard that's not working for them.",
    },
    problem: {
      title: "An unused yard is a quiet drain on a home.",
      body: "It's the part of the house you spend the most time looking at and the least time using. We design and install spaces that finally pull people outside.",
    },
    finalCta: {
      title: "Plan the yard this season.",
      body: "Tell us about the space — we'll come out, listen, and put a real number on it.",
    },
  },

  interlock: {
    slug: "interlock",
    label: "Interlock",
    categoryGroup: "home-services-outdoor",
    estimatedLeadValue: 1400,
    defaultServices: ["Driveways", "Walkways", "Patios", "Steps", "Repairs"],
    buyerPains: ["Cracked driveway", "Curb appeal", "Trip hazards", "Drainage", "Sale prep"],
    highValueServices: ["Full driveway", "Driveway + walkway combo"],
    leadMagnet: "Interlock Project Estimate",
    primaryCTA: "Get an Interlock Estimate",
    secondaryCTA: "Send Photos for a Fast Quote",
    quoteFlow: [
      { id: "projectType", question: "What are we doing?", type: "choice", options: ["Driveway", "Walkway", "Patio", "Steps", "Repair"], required: true },
      { id: "size", question: "Approx size", type: "choice", options: ["Small", "Medium", "Large", "Not sure"] },
      { id: "condition", question: "Current condition", type: "choice", options: ["New build", "Needs replacement", "Needs repair", "Just exploring"] },
      { id: "photo", question: "Photos (optional)", type: "upload" },
      { id: "timeline", question: "When?", type: "choice", options: ["ASAP", "This season", "Next season"] },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["Local crew", "Real projects", "Written quote", "Workmanship warranty", "Free site visit"],
    faqs: [
      { q: "Do you guarantee against settling?", a: "Yes — base prep is the difference. Our warranty covers settling within terms." },
      { q: "How long is a driveway?", a: "Most driveways are 2–4 days depending on prep." },
      { q: "Do you remove the old surface?", a: "Yes, included in the quote." },
    ],
    riskReducers: ["Free site visit", "Written quote", "Stage payments", "Warranty"],
    visualDirection: "Stacked patio terrain layers with stone/grass material.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "stone-warm",
    motionPreset: "cinematic-pin",
    threeDPreset: "terrain-layers",
    accentColor: "#d8b86a",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "The first thing every visitor sees.",
      subheadline: "Interlock driveways, walkways and patios in {city} — built on real base prep.",
    },
    problem: {
      title: "Bad base prep is why interlock fails.",
      body: "Most callbacks are because the work below the stone wasn't done right. We over-spec the base so the surface stays put.",
    },
    finalCta: {
      title: "Get a real interlock quote.",
      body: "Tell us the project, we'll come measure and write up the details.",
    },
  },

  concrete: {
    slug: "concrete",
    label: "Concrete",
    categoryGroup: "home-services-outdoor",
    estimatedLeadValue: 1300,
    defaultServices: ["Driveways", "Slabs", "Steps", "Foundations", "Repairs"],
    buyerPains: ["Cracked driveway", "Poor curb appeal", "Safety", "Durability"],
    highValueServices: ["Full driveway pour", "Stamped concrete"],
    leadMagnet: "Concrete Project Estimate",
    primaryCTA: "Get a Free Concrete Quote",
    secondaryCTA: "Send Photos for Faster Pricing",
    quoteFlow: [
      { id: "projectType", question: "What are we pouring?", type: "choice", options: ["Driveway", "Slab/pad", "Steps", "Walkway", "Repair"], required: true },
      { id: "size", question: "Approx size", type: "choice", options: ["Small", "Medium", "Large", "Not sure"] },
      { id: "condition", question: "Current condition", type: "choice", options: ["New build", "Replacement", "Repair", "Just exploring"] },
      { id: "photo", question: "Photos (optional)", type: "upload" },
      { id: "timeline", question: "When would you like it done?", type: "choice", options: ["ASAP", "This season", "Next season"] },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["Local crew", "Photo-documented work", "Written quote", "Warranty", "Free site visit"],
    faqs: [
      { q: "How long until I can use it?", a: "Foot traffic in 24–48 hours, vehicles depend on the pour — we'll specify per project." },
      { q: "Stamped concrete?", a: "Yes, with patterns and color matched on a sample." },
      { q: "Removal?", a: "Included in the quote." },
    ],
    riskReducers: ["Free site visit", "Written quote", "Workmanship warranty"],
    visualDirection: "Industrial precision with brushed steel/concrete material.",
    designSystem: "industrial-premium",
    themePreset: "steel-amber",
    motionPreset: "industrial-precision",
    threeDPreset: "terrain-layers",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Concrete that lasts longer than the warranty.",
      subheadline: "Driveways, slabs and repairs in {city} — built right the first pour.",
    },
    problem: {
      title: "Cheap pours are tomorrow's cracks.",
      body: "Mix, prep, reinforcement and finishing all matter. We do them all and document every step.",
    },
    finalCta: {
      title: "Get a real concrete quote.",
      body: "We'll measure, spec and write it up — no pressure.",
    },
  },

  "windows-doors": {
    slug: "windows-doors",
    label: "Windows & Doors",
    categoryGroup: "home-services-contractor",
    estimatedLeadValue: 1600,
    defaultServices: ["Window replacement", "Patio doors", "Front doors", "Storm doors"],
    buyerPains: ["Drafts", "Energy bills", "Old/ugly windows", "Curb appeal", "Security"],
    highValueServices: ["Full home window package", "Front door + sidelights"],
    leadMagnet: "Energy Savings Check",
    primaryCTA: "Get a Free Window/Door Estimate",
    secondaryCTA: "Send Photos for a Fast Quote",
    quoteFlow: [
      { id: "product", question: "What are we replacing?", type: "choice", options: ["Windows", "Patio door", "Front door", "Multiple"], required: true },
      { id: "quantity", question: "How many windows/doors?", type: "choice", options: ["1–3", "4–8", "9+", "Whole home"] },
      { id: "issue", question: "Main reason?", type: "choice", options: ["Drafts/energy", "Look", "Damage", "Security"] },
      { id: "photo", question: "Photos (optional)", type: "upload" },
      { id: "timeline", question: "When?", type: "choice", options: ["ASAP", "This season", "Next season"] },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["ENERGY STAR products", "Local install crew", "Written warranty", "Free in-home consult"],
    faqs: [
      { q: "Are estimates free?", a: "Yes, free in-home measurement and consult." },
      { q: "Energy rebates?", a: "Where available — we'll guide you through the program." },
      { q: "How long does install take?", a: "Most homes are 1–2 days." },
    ],
    riskReducers: ["Free consult", "Written warranty", "ENERGY STAR products"],
    visualDirection: "Cinematic dark with thermal heat loss visualization.",
    designSystem: "contractor-cinematic-dark",
    themePreset: "thermal-orange",
    motionPreset: "cinematic-pin",
    threeDPreset: "house-heat-loss",
    accentColor: "#ff8a3d",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Your windows might be the most expensive part of the house.",
      subheadline: "Energy-rated windows and doors in {city}. Free measurement, written warranty.",
    },
    problem: {
      title: "Old windows leak more than you think.",
      body: "Drafts, condensation, ice — these aren't cosmetic, they're literally money escaping. New windows are the rare upgrade that pays itself back.",
    },
    finalCta: {
      title: "See what new windows would actually do.",
      body: "Free in-home measure, written quote, real energy numbers.",
    },
  },

  "pest-control": {
    slug: "pest-control",
    label: "Pest Control",
    categoryGroup: "home-services-recurring",
    estimatedLeadValue: 350,
    defaultServices: ["General pest", "Wasps & hornets", "Rodents", "Bed bugs", "Cockroaches"],
    buyerPains: ["Active infestation", "Recurring issue", "Safety with kids/pets", "Embarrassment"],
    highValueServices: ["Annual plan", "Multi-treatment package"],
    leadMagnet: "Pest Severity Check",
    primaryCTA: "Get a Pest Inspection",
    secondaryCTA: "Send a Photo for Identification",
    quoteFlow: [
      { id: "pest", question: "What's the pest?", type: "choice", options: ["Wasps/hornets", "Mice/rats", "Cockroaches", "Bed bugs", "Ants", "Other / not sure"], required: true },
      { id: "severity", question: "How bad is it?", type: "choice", options: ["Just spotted", "Recurring", "Heavy infestation"], required: true },
      { id: "location", question: "Where in the home?", type: "choice", options: ["Kitchen", "Bedroom", "Basement", "Outside", "Multiple"] },
      { id: "photo", question: "Photo (optional)", type: "upload" },
      { id: "urgency", question: "How fast?", type: "choice", options: ["Today", "This week", "This month"] },
      { id: "contact", question: "Where to send the visit time", type: "contact", required: true },
    ],
    trustPoints: ["Licensed technicians", "Pet/kid-safe treatments", "Discreet visits", "Follow-up included"],
    faqs: [
      { q: "Is it safe for pets?", a: "Yes — we use treatments rated for homes with pets and kids and explain re-entry times." },
      { q: "Will it come back?", a: "Treatment plans include follow-up. Recurring issues get a recurring plan." },
      { q: "How fast?", a: "Most areas same-day or next-day during the season." },
    ],
    riskReducers: ["Discreet, unmarked visits", "Re-treatment guarantee", "Pet-safe options"],
    visualDirection: "Friendly bright with subtle abstract particle field.",
    designSystem: "home-service-motion",
    themePreset: "fresh-green",
    motionPreset: "friendly-fast",
    threeDPreset: "abstract-orb",
    accentColor: "#16a34a",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Get the pest out — quietly, quickly, safely.",
      subheadline: "Discreet pest control in {city}. Pet-safe options, follow-up included.",
    },
    problem: {
      title: "A pest problem doesn't go away on its own.",
      body: "Most call far too late. The earlier we treat, the smaller the job and the more permanent the result.",
    },
    finalCta: {
      title: "Book a discreet inspection.",
      body: "Tell us what you've seen — we'll handle the rest.",
    },
  },

  cleaning: {
    slug: "cleaning",
    label: "Cleaning",
    categoryGroup: "home-services-recurring",
    estimatedLeadValue: 280,
    defaultServices: ["Recurring residential", "Move-in/out", "Deep clean", "Post-renovation", "Commercial"],
    buyerPains: ["No time", "Move stress", "Trust", "Inconsistent past cleaners"],
    highValueServices: ["Recurring contract", "Post-renovation deep clean"],
    leadMagnet: "Fast Cleaning Quote",
    primaryCTA: "Get a Fast Cleaning Quote",
    secondaryCTA: "Book a Trial Clean",
    quoteFlow: [
      { id: "type", question: "What kind of clean?", type: "choice", options: ["One-time deep", "Recurring", "Move-in / move-out", "Post-renovation"], required: true },
      { id: "size", question: "Place size", type: "choice", options: ["Studio/1-bed", "2-bed", "3-bed", "4+ bed", "Commercial"] },
      { id: "bathrooms", question: "Number of bathrooms", type: "choice", options: ["1", "2", "3", "4+"] },
      { id: "timeline", question: "When?", type: "choice", options: ["This week", "Next week", "This month"] },
      { id: "contact", question: "Where to send the quote", type: "contact", required: true },
    ],
    trustPoints: ["Vetted cleaners", "Insured", "Same crew when possible", "Re-clean guarantee"],
    faqs: [
      { q: "What if I'm not satisfied?", a: "Let us know within 24 hours and we re-clean the area free." },
      { q: "Same cleaner each time?", a: "We do our best to keep the same crew on recurring visits." },
      { q: "Do I need to be home?", a: "No — we coordinate access ahead of the visit." },
    ],
    riskReducers: ["Re-clean guarantee", "Vetted insured cleaners", "Cancel anytime"],
    visualDirection: "Bright, friendly, sparkle particles, premium-clean feel.",
    designSystem: "home-service-motion",
    themePreset: "clean-blue",
    motionPreset: "friendly-fast",
    threeDPreset: "abstract-orb",
    accentColor: "#0ea5e9",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Walk into a place that feels new again.",
      subheadline: "Reliable, vetted cleaning in {city}. Trial clean available.",
    },
    problem: {
      title: "Cleaning is the easiest weekend back.",
      body: "Most people who try recurring cleaning never go back to doing it themselves. We make sure the first clean earns the next one.",
    },
    finalCta: {
      title: "Get a fast cleaning quote.",
      body: "Tell us about the place — quote in minutes.",
    },
  },

  dentists: {
    slug: "dentists",
    label: "Dentists",
    categoryGroup: "medical-dental",
    estimatedLeadValue: 800,
    defaultServices: ["Cleanings & checkups", "Cosmetic", "Invisalign", "Implants", "Emergency"],
    buyerPains: ["Confidence with smile", "Treatment uncertainty", "Cost", "Fear", "Financing"],
    highValueServices: ["Implants", "Invisalign", "Full cosmetic"],
    leadMagnet: "Smile Consultation Quiz",
    primaryCTA: "Book a Smile Consultation",
    secondaryCTA: "Take the Smile Quiz",
    quoteFlow: [
      { id: "concern", question: "What brings you in?", type: "choice", options: ["Cleaning / checkup", "Cosmetic improvement", "Straightening", "Pain or emergency", "Just exploring"], required: true },
      { id: "treatmentInterest", question: "Anything specific you've thought about?", type: "choice", options: ["Whitening", "Veneers", "Invisalign", "Implants", "Not sure"] },
      { id: "timeline", question: "When would you like to come in?", type: "choice", options: ["This week", "This month", "Just exploring"] },
      { id: "financing", question: "Want financing options?", type: "choice", options: ["Yes", "No", "Maybe"] },
      { id: "contact", question: "Where to send the appointment time", type: "contact", required: true },
    ],
    trustPoints: ["Licensed clinic", "Modern equipment", "Gentle approach", "Financing available"],
    faqs: [
      { q: "Are consultations free?", a: "Yes — for cosmetic and Invisalign cases." },
      { q: "Do you take new patients?", a: "Yes." },
      { q: "Insurance?", a: "Direct billing with most major insurers." },
    ],
    riskReducers: ["Free cosmetic consults", "Financing", "Direct billing", "Gentle approach"],
    visualDirection: "Clean clinical with enamel-orb and soft lights.",
    designSystem: "medical-clean-3d",
    themePreset: "clinical-blue",
    motionPreset: "calm-clinical",
    threeDPreset: "tooth-orb",
    accentColor: "#2563eb",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "A smile you don't think about hiding.",
      subheadline: "Modern, gentle dental care in {city}. New patients welcome.",
    },
    problem: {
      title: "Most people put it off for years.",
      body: "We make the first visit easy — clear answers, calm room, no judgment, and a plan you actually understand.",
    },
    finalCta: {
      title: "Book a consultation.",
      body: "Tell us what you're thinking about — we'll handle the rest.",
    },
  },

  orthodontists: {
    slug: "orthodontists",
    label: "Orthodontists",
    categoryGroup: "medical-dental",
    estimatedLeadValue: 1200,
    defaultServices: ["Invisalign", "Braces", "Adult ortho", "Teen ortho"],
    buyerPains: ["Self-conscious smile", "Adult treatment hesitation", "Cost / financing"],
    highValueServices: ["Full Invisalign case", "Braces case"],
    leadMagnet: "Free Smile Assessment",
    primaryCTA: "Book a Free Smile Assessment",
    secondaryCTA: "See Treatment Options",
    quoteFlow: [
      { id: "ageGroup", question: "Who's the patient?", type: "choice", options: ["Adult", "Teen", "Child", "Multiple"], required: true },
      { id: "concern", question: "Main concern", type: "choice", options: ["Crowding", "Spacing", "Bite", "Just curious"], required: true },
      { id: "interest", question: "Any preference?", type: "choice", options: ["Invisalign", "Braces", "Whatever's best"] },
      { id: "financing", question: "Want financing options?", type: "choice", options: ["Yes", "No", "Maybe"] },
      { id: "contact", question: "Where to send the time", type: "contact", required: true },
    ],
    trustPoints: ["Licensed orthodontists", "Modern scanners", "In-house financing", "Discreet adult care"],
    faqs: [
      { q: "Is the assessment free?", a: "Yes — full smile assessment is free." },
      { q: "How long is treatment?", a: "Most cases run 12–24 months — we'll give you a real range." },
      { q: "Adult cases?", a: "Yes, the majority of new patients are adults." },
    ],
    riskReducers: ["Free assessment", "Financing", "Discreet treatment options"],
    visualDirection: "Clean clinical with calm motion and enamel orb.",
    designSystem: "medical-clean-3d",
    themePreset: "clinical-blue",
    motionPreset: "calm-clinical",
    threeDPreset: "tooth-orb",
    accentColor: "#2563eb",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "The smile you've thought about for years.",
      subheadline: "Free smile assessment in {city}. Adults welcome — discreet options available.",
    },
    problem: {
      title: "Most adults assume the door already closed.",
      body: "It hasn't. Modern Invisalign and clear options make adult treatment normal — and faster than people expect.",
    },
    finalCta: {
      title: "Book your free smile assessment.",
      body: "We'll show you what's possible and how long it would take.",
    },
  },

  "med-spas": {
    slug: "med-spas",
    label: "Med Spas",
    categoryGroup: "medical-aesthetic",
    estimatedLeadValue: 600,
    defaultServices: ["Botox", "Filler", "Laser", "Skin treatments", "Body treatments"],
    buyerPains: ["Natural results", "Choosing the right treatment", "Safety", "Downtime"],
    highValueServices: ["Treatment series", "Combo packages"],
    leadMagnet: "Treatment Match Quiz",
    primaryCTA: "Find My Treatment Fit",
    secondaryCTA: "Book a Free Consult",
    quoteFlow: [
      { id: "concern", question: "What's your main concern?", type: "choice", options: ["Skin texture", "Lines / wrinkles", "Volume / lift", "Body contouring", "Brightness", "Not sure"], required: true },
      { id: "result", question: "What result do you want?", type: "choice", options: ["Natural refresh", "Visible improvement", "Major change"], required: true },
      { id: "timeline", question: "When would you like to start?", type: "choice", options: ["This month", "Next 3 months", "Just exploring"] },
      { id: "interest", question: "Any treatment in mind?", type: "choice", options: ["Botox", "Filler", "Laser", "Facials", "Not sure"] },
      { id: "contact", question: "Where to send the consult time", type: "contact", required: true },
    ],
    trustPoints: ["Medical-grade", "Licensed practitioners", "Real before/after", "Honest if a treatment isn't right for you"],
    faqs: [
      { q: "Is the consult free?", a: "Yes — full treatment consult is free with no commitment." },
      { q: "Will it look natural?", a: "Our standard is 'noticed but not obvious'. We'll show you real before/after." },
      { q: "Downtime?", a: "Most treatments have minimal downtime — we'll specify per option." },
    ],
    riskReducers: ["Free consult", "Honest treatment fit", "Real before/after"],
    visualDirection: "Luxury wellness glass with glow sphere and soft gradients.",
    designSystem: "luxury-wellness-glass",
    themePreset: "rose-glow",
    motionPreset: "editorial-glass",
    threeDPreset: "glow-sphere",
    accentColor: "#c97a8b",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Refreshed. Not redone.",
      subheadline: "Medical-grade aesthetic care in {city}. Natural results, honest consults.",
    },
    problem: {
      title: "Most clinics sell treatments. We match them.",
      body: "The wrong treatment is worse than no treatment. We start with what you actually want and work backwards from there.",
    },
    finalCta: {
      title: "Find your treatment fit.",
      body: "Take the quiz or book a free consult — no pressure to book anything.",
    },
  },

  "tattoo-shops": {
    slug: "tattoo-shops",
    label: "Tattoo Shops",
    categoryGroup: "personal-aesthetic",
    estimatedLeadValue: 350,
    defaultServices: ["Custom tattoos", "Cover-ups", "Walk-ins", "Touch-ups"],
    buyerPains: ["Choosing artist", "Trust with first tattoo", "Cover-up uncertainty"],
    highValueServices: ["Large custom pieces", "Sleeves"],
    leadMagnet: "Free Design Consult",
    primaryCTA: "Book a Free Design Consult",
    secondaryCTA: "Send Reference Photos",
    quoteFlow: [
      { id: "type", question: "What are you thinking?", type: "choice", options: ["First tattoo", "Custom piece", "Cover-up", "Touch-up"], required: true },
      { id: "size", question: "Approx size", type: "choice", options: ["Small", "Medium", "Large", "Sleeve"] },
      { id: "style", question: "Style", type: "choice", options: ["Fine line", "Black & grey", "Color", "Traditional", "Realism", "Not sure"] },
      { id: "photo", question: "Reference photos (optional)", type: "upload" },
      { id: "contact", question: "Where to send the consult time", type: "contact", required: true },
    ],
    trustPoints: ["Licensed shop", "Sterile, single-use needles", "Real artist portfolios", "Free design consult"],
    faqs: [
      { q: "Is consult free?", a: "Yes — free design consults to get the idea right before booking." },
      { q: "Walk-ins?", a: "Yes, depending on availability." },
      { q: "Touch-ups?", a: "Free touch-ups within terms." },
    ],
    riskReducers: ["Free consult", "Free touch-up", "Real portfolios"],
    visualDirection: "Industrial premium with steel/dark ink mood.",
    designSystem: "industrial-premium",
    themePreset: "ink-amber",
    motionPreset: "industrial-precision",
    threeDPreset: "abstract-orb",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "A tattoo you'll still love in 20 years.",
      subheadline: "Custom design + clean process in {city}. Free consults.",
    },
    problem: {
      title: "Most regret comes from rushing the design.",
      body: "We slow down the front of the process — concept, layout, sizing — so the tattoo holds up.",
    },
    finalCta: {
      title: "Book a design consult.",
      body: "Send what you're thinking — we'll come back with concepts.",
    },
  },

  barbers: {
    slug: "barbers",
    label: "Barbers",
    categoryGroup: "personal-aesthetic",
    estimatedLeadValue: 60,
    defaultServices: ["Haircuts", "Beard work", "Hot towel shave", "Kids cuts"],
    buyerPains: ["Trust with new barber", "Wait time", "Consistency"],
    highValueServices: ["Recurring memberships", "Beard packages"],
    leadMagnet: "Online Booking",
    primaryCTA: "Book a Cut",
    secondaryCTA: "See the Shop",
    quoteFlow: [
      { id: "service", question: "What are you booking?", type: "choice", options: ["Cut", "Cut + beard", "Beard only", "Kids cut"], required: true },
      { id: "barber", question: "Preferred barber?", type: "choice", options: ["No preference", "Specific name"] },
      { id: "timeline", question: "When?", type: "choice", options: ["Today", "This week", "Next week"] },
      { id: "contact", question: "Where to confirm the time", type: "contact", required: true },
    ],
    trustPoints: ["Real reviews", "Walk-ins welcome", "Modern shop", "Beard specialists"],
    faqs: [
      { q: "Walk-ins?", a: "Yes, depending on chair availability." },
      { q: "Same barber each time?", a: "Yes — book by name to lock it in." },
      { q: "Kids?", a: "Yes." },
    ],
    riskReducers: ["Easy reschedule", "Walk-ins welcome"],
    visualDirection: "Industrial premium with warm amber accent.",
    designSystem: "industrial-premium",
    themePreset: "amber-shop",
    motionPreset: "industrial-precision",
    threeDPreset: "abstract-orb",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "A cut you don't have to redo at home.",
      subheadline: "Modern barbers in {city}. Book online or walk in.",
    },
    problem: {
      title: "A bad cut is two weeks of regret.",
      body: "We listen first. We don't rush. And we keep notes so the next cut is even better.",
    },
    finalCta: {
      title: "Book a cut.",
      body: "Pick a time — we'll handle the rest.",
    },
  },

  "cosmetic-clinics": {
    slug: "cosmetic-clinics",
    label: "Cosmetic Clinics",
    categoryGroup: "medical-aesthetic",
    estimatedLeadValue: 800,
    defaultServices: ["Aesthetic medicine", "Skin", "Body", "Laser", "Wellness"],
    buyerPains: ["Choosing right treatment", "Safety", "Natural results"],
    highValueServices: ["Programs", "Combo treatments"],
    leadMagnet: "Treatment Match Quiz",
    primaryCTA: "Book a Free Consult",
    secondaryCTA: "Take the Quiz",
    quoteFlow: [
      { id: "concern", question: "Main concern", type: "choice", options: ["Skin", "Lines", "Volume", "Body", "Wellness"], required: true },
      { id: "result", question: "Desired result", type: "choice", options: ["Natural refresh", "Visible improvement", "Major change"] },
      { id: "interest", question: "Treatment in mind?", type: "choice", options: ["Yes", "No", "Open to ideas"] },
      { id: "contact", question: "Where to send the consult time", type: "contact", required: true },
    ],
    trustPoints: ["Licensed clinicians", "Real before/after", "Honest fit", "Modern equipment"],
    faqs: [
      { q: "Free consult?", a: "Yes — full consult is free." },
      { q: "Natural results?", a: "Yes — that's the standard, not the upsell." },
    ],
    riskReducers: ["Free consult", "Honest treatment fit", "Real before/after"],
    visualDirection: "Luxury wellness glass with rose accent.",
    designSystem: "luxury-wellness-glass",
    themePreset: "rose-glow",
    motionPreset: "editorial-glass",
    threeDPreset: "glow-sphere",
    accentColor: "#c97a8b",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "Care that leaves you looking like you.",
      subheadline: "Modern cosmetic medicine in {city}. Free, honest consults.",
    },
    problem: {
      title: "The right treatment is a quiet upgrade.",
      body: "We start with the result you want and reverse-engineer the plan — not the other way around.",
    },
    finalCta: {
      title: "Book a consult.",
      body: "Tell us what you're thinking. We'll be honest about what's possible.",
    },
  },

  "basement-renovation": {
    slug: "basement-renovation",
    label: "Basement Renovation",
    categoryGroup: "home-services-renovation",
    estimatedLeadValue: 4000,
    defaultServices: ["Full basement", "Apartment / suite", "Bathroom add", "Bar / theatre", "Permits"],
    buyerPains: ["Wasted square footage", "Rental income potential", "Family room", "Permits"],
    highValueServices: ["Full basement apartment", "Full basement build-out"],
    leadMagnet: "Basement Project Estimate",
    primaryCTA: "Get a Basement Quote",
    secondaryCTA: "See Recent Builds",
    quoteFlow: [
      { id: "scope", question: "What kind of project?", type: "choice", options: ["Full basement", "Apartment / suite", "Bathroom add", "Bar / theatre", "Just exploring"], required: true },
      { id: "size", question: "Approx size", type: "choice", options: ["Under 600 sq ft", "600–1,000", "1,000–1,500", "1,500+"] },
      { id: "permits", question: "Permits needed?", type: "choice", options: ["Yes", "No", "Not sure"] },
      { id: "budget", question: "Comfort range", type: "choice", options: ["Under $40k", "$40k–$80k", "$80k–$120k", "$120k+"] },
      { id: "photo", question: "Photos of the space (optional)", type: "upload" },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["Permit handling", "Real installed projects", "Written quote", "Stage payments", "Workmanship warranty"],
    faqs: [
      { q: "Permits?", a: "We handle the application process and inspections." },
      { q: "Timeline?", a: "Most full basements are 8–14 weeks." },
      { q: "Live in the home during work?", a: "Usually yes, with planning." },
    ],
    riskReducers: ["Free site visit", "Written quote", "Stage payments", "Workmanship warranty"],
    visualDirection: "Industrial premium with build-out feel.",
    designSystem: "industrial-premium",
    themePreset: "steel-amber",
    motionPreset: "industrial-precision",
    threeDPreset: "abstract-orb",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "A basement that earns its square footage.",
      subheadline: "Full basement build-outs and legal suites in {city}.",
    },
    problem: {
      title: "Most basements are storage. They could be a floor.",
      body: "Whether it's family space or rental income, it's the cheapest square footage you'll ever build.",
    },
    finalCta: {
      title: "Get a real basement quote.",
      body: "We'll come measure, talk about permits, and put a number on it.",
    },
  },

  "kitchen-renovation": {
    slug: "kitchen-renovation",
    label: "Kitchen Renovation",
    categoryGroup: "home-services-renovation",
    estimatedLeadValue: 5000,
    defaultServices: ["Full kitchen", "Cabinet refresh", "Counter + backsplash", "Layout change"],
    buyerPains: ["Outdated kitchen", "Bad layout", "Selling soon", "Family upgrade"],
    highValueServices: ["Full custom kitchen", "Layout change"],
    leadMagnet: "Kitchen Project Estimate",
    primaryCTA: "Get a Kitchen Quote",
    secondaryCTA: "See Recent Kitchens",
    quoteFlow: [
      { id: "scope", question: "What's the project?", type: "choice", options: ["Full reno", "Cabinet refresh", "Counter + backsplash", "Layout change", "Just exploring"], required: true },
      { id: "size", question: "Kitchen size", type: "choice", options: ["Galley", "Standard", "Open concept", "Large open"] },
      { id: "budget", question: "Comfort range", type: "choice", options: ["Under $25k", "$25k–$50k", "$50k–$80k", "$80k+"] },
      { id: "timeline", question: "When?", type: "choice", options: ["ASAP", "1–3 months", "3–6 months"] },
      { id: "photo", question: "Photos of the space (optional)", type: "upload" },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["Real installed kitchens", "Detailed quote", "In-house design", "Workmanship warranty"],
    faqs: [
      { q: "Timeline?", a: "Most full kitchens are 4–8 weeks once materials arrive." },
      { q: "Design?", a: "In-house design with 3D layout review." },
      { q: "Live in the home?", a: "Usually yes, with kitchen-out planning." },
    ],
    riskReducers: ["Free design call", "Detailed quote", "Stage payments", "Workmanship warranty"],
    visualDirection: "Industrial premium with warm amber accent.",
    designSystem: "industrial-premium",
    themePreset: "steel-amber",
    motionPreset: "industrial-precision",
    threeDPreset: "abstract-orb",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "The kitchen that finally fits how you actually cook.",
      subheadline: "In-house design + install in {city}. Real numbers, real timelines.",
    },
    problem: {
      title: "Bad layouts ruin great kitchens.",
      body: "We design around how you actually move and use the space — not just what looks good in renderings.",
    },
    finalCta: {
      title: "Get a real kitchen quote.",
      body: "Tell us about the space — we'll design around it.",
    },
  },

  "bathroom-renovation": {
    slug: "bathroom-renovation",
    label: "Bathroom Renovation",
    categoryGroup: "home-services-renovation",
    estimatedLeadValue: 3500,
    defaultServices: ["Full bathroom", "Walk-in shower", "Tub-to-shower", "Powder room"],
    buyerPains: ["Outdated bathroom", "Mold / damage", "Aging in place", "Selling soon"],
    highValueServices: ["Full ensuite", "Tub-to-shower conversion"],
    leadMagnet: "Bathroom Project Estimate",
    primaryCTA: "Get a Bathroom Quote",
    secondaryCTA: "See Recent Bathrooms",
    quoteFlow: [
      { id: "scope", question: "What's the project?", type: "choice", options: ["Full reno", "Walk-in shower", "Tub-to-shower", "Powder room", "Just exploring"], required: true },
      { id: "issues", question: "Any current issues?", type: "choice", options: ["Leaks / damage", "Mold", "Just outdated", "Layout"] },
      { id: "budget", question: "Comfort range", type: "choice", options: ["Under $15k", "$15k–$30k", "$30k–$50k", "$50k+"] },
      { id: "timeline", question: "When?", type: "choice", options: ["ASAP", "1–3 months", "3–6 months"] },
      { id: "photo", question: "Photos of the space (optional)", type: "upload" },
      { id: "contact", question: "Where to send the estimate", type: "contact", required: true },
    ],
    trustPoints: ["Real installed bathrooms", "Detailed quote", "Waterproofing-focused", "Workmanship warranty"],
    faqs: [
      { q: "Timeline?", a: "Most full bathrooms are 2–4 weeks." },
      { q: "Waterproofing?", a: "Yes — non-negotiable. We document it." },
      { q: "Live in the home?", a: "Usually yes, with planning around the work." },
    ],
    riskReducers: ["Free in-home consult", "Detailed quote", "Stage payments", "Workmanship warranty"],
    visualDirection: "Industrial premium with cool tile accent.",
    designSystem: "industrial-premium",
    themePreset: "steel-amber",
    motionPreset: "industrial-precision",
    threeDPreset: "abstract-orb",
    accentColor: "#f5b301",
    sectionOrder: baseSectionOrder,
    heroFormula: {
      headline: "A bathroom that finally feels like the rest of the house.",
      subheadline: "Full bathroom renovations in {city}. Detailed quotes, real timelines.",
    },
    problem: {
      title: "Bathrooms fail at the waterproofing.",
      body: "We over-spec the membrane work. The tile is the easy part.",
    },
    finalCta: {
      title: "Get a real bathroom quote.",
      body: "Tell us about the space — we'll come measure and write it up.",
    },
  },
};

export function getNichePreset(slug: string): NichePreset {
  return NICHE_PRESETS[slug] ?? NICHE_PRESETS["roofing"];
}

export const NICHE_LIST = Object.values(NICHE_PRESETS);

export const DEFAULT_CITIES = [
  { name: "Mississauga", region: "ON", country: "CA" },
  { name: "Brampton", region: "ON", country: "CA" },
  { name: "Toronto", region: "ON", country: "CA" },
  { name: "Etobicoke", region: "ON", country: "CA" },
  { name: "Vaughan", region: "ON", country: "CA" },
  { name: "Oakville", region: "ON", country: "CA" },
  { name: "Burlington", region: "ON", country: "CA" },
  { name: "Markham", region: "ON", country: "CA" },
  { name: "Richmond Hill", region: "ON", country: "CA" },
];
